Develop departement
audipasuatmadi/msdm-frontend pull request #19
Opened 2021-04-19 12:22 UTC by krisnadwipayana07

2021-04-19 12:32 UTC, audipasuatmadi requested changes

2021-04-19 12:32 UTC, audipasuatmadi commented on src/pages/Departement/Departement.js
> +      deskripsi : deskripsi,
Coba ganti `nama` ke `name`, deskripsi ke `description`

Jadinya:

```js
const shippingData = {
  name: nama,
  description: deskripsi
};
```

2021-04-19 12:32 UTC, audipasuatmadi commented on src/pages/Departement/Departement.js
> +                )[0];
coba ganti dari `data`.filter ke `departemenData`.filter

2021-04-19 12:35 UTC, krisnadwipayana07 commented on src/pages/Departement/Departement.js
> +      deskripsi : deskripsi,
jadinya name: name gitu kak?

2021-04-26 08:13 UTC, merged

2021-05-08 02:40 UTC, audipasuatmadi commented on src/pages/Departement/Departement.js
> +    }
Ubah ini ke bla bla bla